config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :products
  resources :carts
  resources :wishlists
  resources :categories
  devise_for :sellers
  devise_for :users
  post '/addtocart'=>'cart_items#add_to_cart'
  get 'home/index'
  root 'home#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items

  def self.calculate_sub_total_price cart_id
  	new_sub_total_price=0
  	# byebug
  	cart=Cart.find(cart_id)
  	cart.cart_items.each do |cart_item|
  		puts "khd"
  		new_sub_total_price=new_sub_total_price+cart_item.total_price_item
  	end
  	return new_sub_total_price
  end
  def self.new_subtotal_price current_cart
  	subtotal_price=calculate_sub_total_price(current_cart.id)
  	total_price=subtotal_price
  	newcrt={subtotal_price:subtotal_price,total_price:total_price}
  	current_cart.update(newcrt)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :current_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @cart = Cart.where(user_id:current_user.id).last
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    # @cart=current_cart
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
    # redirect_to url_for(controller: :cart_items,action: :add_to_cart)
    
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id, :subtotal_price, :total_price)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for @cart , :class => 'form' do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id ,:class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :subtotal_price %><br>
    <%= f.text_field :subtotal_price ,:class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price ,:class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/carts/delete.html.erb
<!-- <table class="table table­striped table­bordered table­hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Subtotal price</th>
      <th>Total price</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @cart.user %></td>
        <td><%= @cart.subtotal_price %></td>
        <td><%= @cart.total_price %></td>
        <td><%= link_to 'Show', @cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(@cart) %></td>
        <td><%= link_to 'Destroy', @cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>

<br> -->

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>


<% if @cart.nil? %>
<h3>Hi <%= current_user.email %> your cart is empty</h3>
<% else %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Product</th>
      <th>Item quantity</th>
      <th>Unit price</th>
      <th>Total price item</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @cart.cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.product.product_name %></td>
        <td><%= cart_item.item_quantity %></td>
        <td><%= cart_item.product.product_cost %></td>
        <td><%= cart_item.total_price_item %></td>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3"><span class="text-center">Subtotal Price</span></td>
      <td><%= @cart.subtotal_price %></td>
    </tr>
    <tr>
      <td colspan="3"><span text-align="center">Total Price</span></td>
      <td><%= @cart.total_price %></td>
    </tr>
  </tfoot>
</table>
<% end %>
<br>
<%= link_to 'New Cart', new_cart_path %> | 
<%= link_to 'Products',products_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user %>
</p>

<p>
  <strong>Subtotal price:</strong>
  <%= @cart.subtotal_price %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @cart.total_price %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>